language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:dns/gnu --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libjansson-dev libnice-dev libssl-dev libsrtp-dev
  - sudo apt-get install -y libglib2.0-dev libogg-dev libini-config-dev libsofia-sip-ua-dev
  - sudo apt-get install -y libcollection-dev libavutil-dev libavcodec-dev libavformat-dev
  - sudo apt-get install -y libtool autoconf automake make bison flex gcc cmake glib-2.0 clang
  - wget https://github.com/cisco/libsrtp/archive/v1.5.0.tar.gz
  - tar xfv v1.5.0.tar.gz
  - cd libsrtp-1.5.0
  - ./configure --prefix=/usr --enable-openssl --libdir=/usr/lib64
  - make libsrtp.so
  - sudo make uninstall
  - sudo make install
  - cd ..
  - git clone https://github.com/meetecho/janus-gateway.git
  - cd janus-gateway
  - ./autogen.sh
  - ./configure --prefix=/opt/janus --disable-docs --disable-rabbitmq --disable-websockets --disable-data-channels
  - make
  - sudo make install
  - cd ..

script:
  - ./autogen.sh
  - ./configure --prefix=/opt/janus
  - make
  - sudo make install
