language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:dns/gnu --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y libtool autoconf automake make bison flex gcc cmake glib-2.0 clang

script:
  - ./autogen.sh
  - ./configure --prefix=/opt/janus
  - make
  - sudo make install
